#!/bin/sh
# File generated by ocamlbuild

cd '/Users/arthur/Documents/Drive Arthur/Travail/L3S2 ENS/Systèmes d'\''exploitation/Projet_OS'

rm -f version_unix.cmi
rm -f version_unix.cmx
rm -f version_unix.o
# Also clean the script itself
rm -f '/Users/arthur/Documents/Drive Arthur/Travail/L3S2 ENS/Systèmes d'\''exploitation/Projet_OS/_build/sanitize.sh'
